# Generated by Django 3.0 on 2026-03-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerous_spot',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
