# Generated by Django 3.0 on 2026-03-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userjourney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourney',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
