# Generated by Django 3.0 on 2026-03-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20260307_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journeyrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('JOURNEY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserJourney')),
                ('SENDERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
