# Generated by Django 3.0 on 2026-03-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sosalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='lid',
        ),
    ]
