# Generated by Django 3.0 on 2026-03-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_sosalert_lid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerous_spot',
            name='type',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
