# Generated by Django 3.0 on 2026-03-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency_contact',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
