# Generated by Django 3.0 on 2026-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_emergency_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
